url: localhost
title: "Comtom Tech"
email: "sales@comtomtech.com"
description: "We are a small development team located in Mar del Plata, Argentina. Apps are our passion. Several years of experience and a great team of developers allows us to build awesome stuff. Request an estimate now, our services are also affordable!"

color:
  primary: 0055d4    
  secondary: 0055d4
  secondarydark: 055ee2

people:
- name: "Pablo Brown"
  pic: 1
  position: "Lead Developer"
  social:
    - title: twitter
      url: "https://twitter.com/pgbrown"
    - title: facebook
      url: "https://facebook.com"
    - title: linkedin
      url: "https://linkedin.com"

- name: "Gabriel Mammoli"
  pic: 2
  position: "Lead Marketer"
  social:
    - title: linkedin
      url: "https://ar.linkedin.com/in/gabrielmammoli"

- name: "Tomás Gonzalez Dowling"
  pic: 3
  position: "Lead Developer"
  social:
    - title: twitter
      url: "https://twitter.com/therealcomtom"
    - title: stack-overflow
      url: "http://stackoverflow.com/users/1945707/tom%C3%A1s-gonzalez-dowling"
    - title: linkedin
      url: "https://linkedin.com"

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: "https://twitter.com/ComtomTech"
  - title: facebook
    url: "https://facebook.com/ComtomTech"
  - title: bitbucket
    url: "https://bitbucket.org/ComtomTech"
  - title: github
    url: "https://github.com/ComtomTech"

# Postal address (add as many lines as necessary)
address:
  - line: "2424 Arenales"
  - line: "Mar del Plata, Buenos Aires 7600"

# Build settings
highlighter: true
markdown: kramdown
permalink: pretty